public class SpirelPartten {
    public static void spirelLength(integer n){
        integer num = 1;
        for(integer i = 0; i<n; i++){
            List<integer> showList = new List<integer>();
            for(integer j = 0; j<n; j++){
                if(i==0){
                    showList.add(num);
                        }
            
                num++;
                
            
        }
            system.debug(showList);
        }
    }
}